#!/bin/bash
OK=0
WARN=1
CRITICAL=2

PLUGIN="/usr/lib/nagios/plugins/check_http"

function printUsage() {
    echo "Usage: $0 --host <ip-address|hostname> --vhosts www.domain1.com,www.domain2.com,... [--port 443] [--mindays 30]"
}

if [ ! -x "$PLUGIN" ]; then
  echo "CRITICAL: Missing $PLUGIN"
  exit $CRITICAL
fi

if [ "$( "$PLUGIN" | grep -o "[-][-]sni" | wc -l)" -ne 1 ]; then
  echo "CRITICAL: Missing support for --sni"
  exit $CRITICAL
fi

PORT=443
DAYS=30
while [ $# -gt 0 ]; do
  if [ "$1" == "--help" ]; then
    shift
    printUsage
    exit $OK
  elif [ "$1" == "--host" ]; then
    shift
    HOST="$1"
    shift
  elif [ "$1" == "--vhosts" ]; then
    shift
    VHOSTS="$1"
    shift
  elif [ "$1" == "--mindays" ]; then
    shift
    DAYS="$1"
    shift
  elif [ "$1" == "--port" ]; then
    shift
    PORT="$1"
    shift
  else
    printUsage
    echo "Unknown parameter: $1"
    exit $CRITICAL
  fi
done

[ -z "$HOST" ] && printUsage && echo "Missing --host parameter" && exit $CRITICAL
[ -z "$VHOSTS" ] && printUsage && echo "Missing --vhosts parameter" && exit $CRITICAL
[ -z "$DAYS" ] && printUsage && echo "Missing --mindays parameter" && exit $CRITICAL

OLD_IFS="$IFS"
IFS=","
EXIT_CODE=$OK
MESSAGE=""
for VHOST in $VHOSTS; do
  OUTPUT="$("$PLUGIN" -I "$HOST" -H "$VHOST" --ssl --sni -p "$PORT" -C "$DAYS")"
  PLUGIN_STATUS=$?
  [ $PLUGIN_STATUS -gt $EXIT_CODE ] && EXIT_CODE=$PLUGIN_STATUS
  [ -n "$MESSAGE" ] && MESSAGE="$MESSAGE :: "
  MESSAGE="${MESSAGE}$VHOST ($OUTPUT)"
done
IFS="$OLD_IFS"
echo "$MESSAGE"
exit $EXIT_CODE
